swagger: "2.0"
info:
  title: "LSTM API"
  description: "API para previsão dos próximos 10 fechamentos da ação GOOG usando LSTM."
  version: "1.0"
basePath: "/"
schemes:
  - "http"
paths:
  /predict:
    post:
      tags:
        - "Prediction"
      summary: "Prevê os próximos 10 fechamentos da ação GOOG"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              features:
                type: "array"
                items:
                  type: "object"
                  properties:
                    Close:
                      type: "number"
                    High:
                      type: "number"
                    Low:
                      type: "number"
                    Open:
                      type: "number"
                    Volume:
                      type: "number"
                example:
                  - { "Close": 123.4, "High": 124.0, "Low": 122.5, "Open": 123.0, "Volume": 1000000 }
                  - { "Close": 124.1, "High": 125.0, "Low": 123.5, "Open": 124.0, "Volume": 1100000 }
                  - { "Close": 125.0, "High": 126.0, "Low": 124.0, "Open": 125.0, "Volume": 1200000 }
                  - { "Close": 124.8, "High": 125.5, "Low": 124.2, "Open": 124.5, "Volume": 1150000 }
                  - { "Close": 126.2, "High": 127.0, "Low": 125.5, "Open": 126.0, "Volume": 1300000 }
                  - { "Close": 127.0, "High": 128.0, "Low": 126.5, "Open": 127.0, "Volume": 1400000 }
                  - { "Close": 128.1, "High": 129.0, "Low": 127.5, "Open": 128.0, "Volume": 1500000 }
                  - { "Close": 129.5, "High": 130.0, "Low": 128.5, "Open": 129.0, "Volume": 1600000 }
                  - { "Close": 130.0, "High": 131.0, "Low": 129.0, "Open": 130.0, "Volume": 1700000 }
                  - { "Close": 131.2, "High": 132.0, "Low": 130.5, "Open": 131.0, "Volume": 1800000 }
            required:
              - features
      responses:
        200:
          description: "Predicted next 10 closing prices"
          schema:
            type: "object"
            properties:
              predictions:
                type: "array"
                items:
                  type: "number"
        400:
          description: "Erro de validação"
  /retrain:
    post:
      tags:
        - "Model"
      summary: "Retreina o modelo LSTM"
      description: "Executa o script de retreino do modelo e recarrega o modelo na API."
      produces:
        - "application/json"
      responses:
        200:
          description: "Retreino realizado com sucesso"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "success"
              output:
                type: "string"
                description: "Saída do script de retreino"
        500:
          description: "Erro ao retreinar o modelo"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "error"
              output:
                type: "string"
              error:
                type: "string"